/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef PHP_SOLVER_H
#define PHP_SOLVER_H

extern zend_module_entry solver_module_entry;
#define phpext_solver_ptr &solver_module_entry

#ifdef PHP_WIN32
# define PHP_SOLVER_API __declspec(dllexport)
#else
# define PHP_SOLVER_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(solver);
PHP_MSHUTDOWN_FUNCTION(solver);
PHP_RINIT_FUNCTION(solver);
PHP_RSHUTDOWN_FUNCTION(solver);
PHP_MINFO_FUNCTION(solver);

ZEND_NAMED_FUNCTION(_wrap_cppMain);
#endif /* PHP_SOLVER_H */
